import { WebForms, HtmlEvent } from "/demo/script/module/WebForms.js";

export function PageLoad(evt)
{
    const form = new WebForms();

    return `
<h2>About WebForms Core</h2>
<p>
WebForms Core consists of a JavaScript library called <b>WebFormsJS</b>, distributed as the physical file <b>web-forms.js</b>, and a general-purpose <b>WebForms</b> God Class that has been ported and made available for 18 programming languages.
</p>
<p>
The WebFormsJS library is added to the <b>&lt;head&gt;</b> section of an HTML page. It acts as the Executor in the WebForms Core architecture, executing the commands generated by the WebForms class and applying them directly to the HTML DOM.
</p>
<p>
Developers build their WebForms Core applications primarily around the <b>WebForms</b> class. The technology is commonly used on the server or in WebAssembly, where the WebForms class generates the commands that are sent to the browser.
</p>
<p>
JavaScript is one of the programming languages for which the WebForms class has been ported. However, the WebForms class is not limited to server-side execution. It can also be used directly on the client side.
</p>
<p>
This demo was built using the <b>WebForms</b> class for JavaScript. The same WebForms Core operations can be implemented on the server using any of the supported programming languages, following the syntax conventions of that language, while producing the same result in the browser.
</p>
<p>
This makes WebForms Core a language-agnostic UI technology: developers can use their preferred server-side programming language while working with the same underlying WebForms Core architecture and client-side Executor.
</p>
    `
}
